fix: Rename template parameter BLOCK_SIZE to avoid macro conflict (#127)
The template parameter `BLOCK_SIZE` used in
`internal/arch/common/unicode_common.h` conflicts with a common macro of
the same name defined in system headers like `<linux/fs.h>` (on
Linux/Android). This causes compilation errors when `<sonic/sonic.h>` is
included after such headers.

This pull request renames the template parameter to prevent this macro
pollution, improving the library's robustness and compatibility in
various build environments.

### Changes

- Renamed the template parameter `BLOCK_SIZE` in
internal/arch/common/unicode_common.h.
- Updated all internal usages of this template parameter to reflect the
new name.


### Reproduce

The fix has been verified by building the following minimal reproducible
example, which now compiles successfully:
```
// g++ -I./include -mpclmul -march=haswell --std=c++11 -O3 thisfile.cpp
#include <linux/fs.h>
#include <sonic/sonic.h>

int main() {
    return 0;
}
```

The compilation error message is shown below:
```
.../include/sonic/internal/arch/neon/../common/unicode_common.h:271:18: error: expected ')'
.../sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/linux/fs.h:29:21: note: expanded from macro 'BLOCK_SIZE'
.../include/sonic/internal/arch/neon/../common/unicode_common.h:271:18: note: to match this '('
.../sdk/ndk/21.1.6352462/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/linux/fs.h:29:20: note: expanded from macro 'BLOCK_SIZE'
```